# Pull base image
FROM python:3.11

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code/

# Install dependencies
COPY poetry.lock .
COPY pyproject.toml .
RUN pip install poetry && \
    poetry config installer.max-workers 10 && \
    poetry config virtualenvs.create false && \
    poetry install --only ui

COPY ./src/app.py /code/src/app.py

EXPOSE 8080